### ISSUE TITLE
images not proper loading in a long report

### ISSUE THREAD

**Issue by BillMa1992** [jsreport/jsreport-phantom-pdf#19]
I met a problem when I'm doing a report where each page has a map image.

I have another jsreport-image template to generate map images using url requests. And then I directly insert the image results into the report. <img src="the url request" stlye="...">

1. It can only properly print the first 12 pages with map images.
2. After setting "phantom": {"strategy": "phantom-server"}, it can properly print first 24 pages.
3. I think that's a problem about enabling disk-cashe and setting its size. However, I don't know where I can set that in jsreport. Does anyone know the place? Thank you!

Best,
Bill

**Comment by bjrmatos** [comment]
hmm maybe your problem is related to the fact that your map images requests are async and phantomjs is not waiting until all images are loaded to start the printing.

have you tried to activate a [printing trigger](https://jsreport.net/learn/phantom-pdf#printing-triggers)? 

you have the option to activate the `waitForJS` option and then you just need to set the `JSREPORT_READY_TO_START = true` variable in the javascript part (`<script>` part) of your template, this will let you control exactly when phantomjs should start printing the page.

for example after activating the `waitForJS` property of your template (a checkbox in jsreport studio) try to put a javascript like this in your template:

```js
// ...html here...
<script>
    // put a fake time, just to see if that your problem is indeed a race condition 
    // between phantomjs and your map images
    setTimeout(function() {
        window.JSREPORT_READY_TO_START = true; //this will start the pdf printing
    }, 5000);
    ...
</script>
```

**Comment by bjrmatos** [comment]
an example to give you and idea: https://playground.jsreport.net/studio/workspace/rkYn7WaCg/19

**Comment by BillMa1992** [comment]
Thanks for your quick response. Yes, it's seems to be the problem. By setting "window.JSREPORT_READY_TO_START = true;" now I get more map successfully printed. However, there are still 2 maps that fail to print.

A lot of warnings like this:
![image](https://user-images.githubusercontent.com/10687700/27297973-c046a1a2-54db-11e7-88c0-a5963bd66439.png)

and the error canceling the print looks like this:
![image](https://user-images.githubusercontent.com/10687700/27298001-e09599fe-54db-11e7-8772-50fbb316a179.png)

**Comment by bjrmatos** [comment]
it is something difficult to tell you what is happening (or if there is any kind of issue) without looking what you have in the template, the first warning seems like an error in the javascript part of your template

can you share here the content of your template (template, helpers etc)?

**Comment by BillMa1992** [comment]
Thanks for your reply. I think the issue can be closed. Since it's something with Phantom.js. I may not use the async strategy to do the printing tasks. Again, thank you for your fast reply!

Best,
Bill
